apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd-desa
  namespace: argocd
spec:

  description: Project to desa
  
  sourceRepos:
  - '*'
  
  destinations:
  - namespace: argocd
    server: https://openshift.desa.svc

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-desa
  namespace: argocd
spec:
  
  project: argocd-desa
  
  source:
    repoURL: https://github.com/lasegunda/argocd-noprod.git
    targetRevision: HEAD
    path: /environments/desa/
  
  destination:
    server: https://openshift.desa.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      allowEmpty: true

