apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd-desa
  namespace: openshift-operators
spec:

  description: Project to desa

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  
  sourceRepos:
  - '*'
  
  destinations:
  - namespace: argocd
    server: https://kubernetes.default.svc

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-desa
  namespace: openshift-operators
spec:
  
  project: argocd-desa
  
  source:
    repoURL: https://github.com/brianwolf/l2da-argocd.git
    targetRevision: HEAD
    path: environments/desa/
  
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      allowEmpty: true

