apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: desa-apps
  namespace: openshift-operators
spec:

  description: Project to dev

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  
  sourceRepos:
  - '*'
  
  destinations:
  - namespace: msdesa
    server: https://kubernetes.default.svc

---

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: desa-3scale
  namespace: openshift-operators
spec:

  description: Project to dev

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  
  sourceRepos:
  - '*'
  
  destinations:
  - namespace: 3scale
    server: https://kubernetes.default.svc